#!/bin/bash

# if is not four
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# label parameters with variable names
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Disable strict host key checking
scp_cmd="scp -o StrictHostKeyChecking=no -i $ssh_key $file_path $username@$server_ip:~/"

# Execute scp command
$scp_cmd

# if scp command worked
if [ $? -eq 0 ]; then
    echo "File transferred successfully to $username@$server_ip:~/"
else
    echo "File transfer failed."
fi

