#!/usr/bin/env bash
# install a web server: Install nginx on your web-01

# Update package and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# giving ownership to user ubuntu
sudo chown -R ubuntu /var/www

# hello world
echo "Hello World!" > /var/www/html/index.html

sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# restart nginx
sudo service nginx start
