#!/usr/bin/env bash
# install a web server: Install nginx on your web-01

# Update package and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

#configuration
sudo mkdir -p /etc/nginx/html

# hello world
echo "Hello World!" > /etc/nginx/html/index.html

# creating the server block
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /etc/nginx/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;
}
" > /etc/nginx/sites-available/default

# restart nginx
sudo service nginx restart
