#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# Update package and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Creating Sample Page
echo "Hello World!" > /var/www/html/index.html

str_redirect="server_name _;\n\trewrite ^\/redirect_me https:\/\/https://www.youtube.com/watch?v=QH2-TGUlwu4;"
sudo sed -i "s/server_name _;/$str_redirect/" /etc/nginx/sites-enabled/default

# restart nginx
sudo service nginx restart
