#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# Update package and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Sample Page
echo "Hello World!" > /var/www/html/index.html

string_for_replacement="server_name _;\\n\\tlocation /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }"
sudo sed -i "s|server_name _|$string_for_replacement|" /etc/nginx/sites-enabled/default

# restart nginx
sudo service nginx restart
