#!/usr/bin/env bash
# install a web server: Install nginx on your web-01

# Update package and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# giving ownership to user ubuntu
sudo chown -R ubuntu /var/www

# hello world
echo "Hello World!" > /var/www/html/index.html

# symbolic link
sudo sed -i '/^\sserver_name.*/a \	rewrite ^redirect_me(/*) https://www.youtube.com/watch?v=QH2-TGUlwu4;' /etc/nginx/sites-avaliable/default

# restart nginx
sudo service nginx reload
