#!/usr/bin/evn bash
# Configure your Nginx server to have a custom 404 page

# Update package information and install Nginx (if not already installed)
sudo apt-get update
sudo apt-get install -y nginx

# Start Nginx without systemctl
sudo service nginx start

# Configure Nginx to listen on port 80, perform redirection, and set a custom 404 page
echo 'server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 http://example.com/newpage; # Replace with your desired redirection URL
    }

    location / {
        echo "Hello World!";
    }

    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }
}' | sudo tee /etc/nginx/sites-available/default

# custom 404 page with the required string
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Reload Nginx configuration
sudo service nginx reload

# if Nginx is not running
if ! pgrep -x "nginx" >/dev/null; then
    echo "Nginx not running."
    exit 1
fi

# if successfull
echo "Nginx configured with a custom 404 page that returns an HTTP 404 error code."

