#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it
MYSQL_PASSWORD="$1"

# Format for the backup
FILE_NAME="$(date +"%d-%m-%Y").tar.gz"

# Dump MySQL databases and compress
mysqldump --user=root --password="$MYSQL_PASSWORD" --all-databases > backup.sql
tar -czf "$FILE_NAME" "backup.sql"
