#!/usr/bin/env bash
# detecting what’s keeping Ubuntu container’s Nginx installation from
# listening on port 80.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
