#!/usr/bin/env bash
# detecting what’s keeping Ubuntu container’s Nginx installation from
# listening on port 80.
sudo sed -i "s/8080 default_server/80 default_server/g" /etc/nginx/sites-enabled/default
service nginx restart
