#!/usr/bin/env bash
# running as nginx user
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
# run on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
# mode
chmod 644 /etc/nginx/sites-available/default
# kill apache so nginx can run on port 8080
pkill apache2
# start nginx
sudo -u nginx service nginx start
