#!/usr/bin/env bash
# Using task #1, make your fix short and sweet;7 lines long or less
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
